### ISSUE TITLE
Landing page conflict

### ISSUE THREAD

**Issue by Ehidiamhen** [zuri-training/TeamGorilla-Auth_wiki#24]
The dev that worked on the home page should have a look at it. Some positioning is clashing with the footer, I tried fixing it but I couldn't. Also, let's have a look at the article I dropped on the group chat, we should refactor our styling to use css modules before our codebase becomes very large and it starts causing major conflicts. Thank you.

**Comment by LeRoiCodes** [comment]
good spot

**Comment by LeRoiCodes** [comment]
solved
